# Generated by Django 4.2.6 on 2023-11-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='auto_park',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
    ]
